CREATE TABLE IF NOT EXISTS invoices (
  id             TEXT PRIMARY KEY,
  entity_id      TEXT NOT NULL,
  book_id        TEXT NOT NULL,
  invoice_no     TEXT NOT NULL,
  invoice_type   TEXT NOT NULL,
  direction      TEXT NOT NULL,
  issue_date     DATE NOT NULL,
  seller_name    TEXT,
  seller_tax_no  TEXT,
  buyer_name     TEXT,
  buyer_tax_no   TEXT,
  amount         NUMERIC(18,2) NOT NULL,
  tax_amount     NUMERIC(18,2) NOT NULL,
  total_amount   NUMERIC(18,2) NOT NULL,
  currency       TEXT NOT NULL DEFAULT 'CNY',
  status         TEXT NOT NULL,
  source         TEXT NOT NULL,
  invoice_kind   TEXT,
  digital_invoice_no TEXT,
  business_tag   TEXT,
  verification_status TEXT DEFAULT 'unchecked',
  usage_status        TEXT DEFAULT 'unconfirmed',
  deduction_status    TEXT DEFAULT 'not_deducted',
  red_letter_status   TEXT DEFAULT 'none',
  original_invoice_id TEXT,
  tax_account_payload TEXT DEFAULT '{}',
  extraction     JSONB NOT NULL DEFAULT '{}',
  evidence_refs  JSONB NOT NULL DEFAULT '[]',
  invoice_lines  JSONB NOT NULL DEFAULT '[]',
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (entity_id, book_id, invoice_no)
);
